"""A minimal OpenAI-compatible LLM client."""

from openai import (
    APIConnectionError,
    APIStatusError,
    AuthenticationError,
    OpenAI,
    RateLimitError,
)

from config import Settings, get_settings


class LLMClient:
    """Client used to send prompts to an OpenAI-compatible API."""

    def __init__(self, settings: Settings) -> None:
        self.settings = settings

        self.client = OpenAI(
            api_key=settings.api_key,
            base_url=settings.base_url,
            timeout=30.0,
            max_retries=2,
        )

    def chat(self, user_message: str) -> str:
        """
        Send one user message and return the model response.

        Args:
            user_message: Text entered by the user.

        Returns:
            Text generated by the model.

        Raises:
            ValueError: If the user message is empty.
            RuntimeError: If the API request fails.
        """
        cleaned_message = user_message.strip()

        if not cleaned_message:
            raise ValueError("输入内容不能为空。")

        try:
            response = self.client.chat.completions.create(
                model=self.settings.model,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "你是一名严谨的学术论文助手。"
                            "回答应当准确、清晰，不编造不存在的信息。"
                        ),
                    },
                    {
                        "role": "user",
                        "content": cleaned_message,
                    },
                ],
            )

            answer = response.choices[0].message.content

            if not answer:
                raise RuntimeError("模型返回了空内容。")

            return answer.strip()

        except AuthenticationError as error:
            raise RuntimeError(
                "API 身份验证失败，请检查 LLM_API_KEY。"
            ) from error

        except RateLimitError as error:
            raise RuntimeError(
                "请求频率过高或账户额度不足，请稍后重试。"
            ) from error

        except APIConnectionError as error:
            raise RuntimeError(
                "无法连接 API，请检查网络和 LLM_BASE_URL。"
            ) from error

        except APIStatusError as error:
            raise RuntimeError(
                f"API 返回异常状态码：{error.status_code}。"
            ) from error


def main() -> None:
    """Run a minimal API call test."""
    try:
        settings = get_settings()
        llm = LLMClient(settings)

        question = "请用两句话解释什么是检索增强生成。"

        print(f"问题：{question}")
        print("正在调用模型……")

        answer = llm.chat(question)

        print("\n模型回答：")
        print(answer)

    except (ValueError, RuntimeError) as error:
        print(f"\n程序运行失败：{error}")


if __name__ == "__main__":
    main()